using System;
using System.Drawing;
using System.Windows.Forms;
using carstore; // Add this line to use the DatabaseConnection class

namespace carstore
{
    public partial class login : Form
    {

        // Add this public property to store the logged-in username
        public string LoggedInUsername { get; private set; }

        // ... existing code for panel and controls declarations ...
        // Panel to hold all login-related controls (dynamically created)
        private Panel pnlLogin;

        // Controls specific to the login panel (dynamically created)
        private Label labelLoginName;
        private TextBox textBoxLoginName;
        private Label labelLoginPassword;
        private TextBox textBoxLoginPassword;
        private Button buttonPerformLogin; // The button for actual login action
        // ... existing code ...

        public login()
        {
            // InitializeComponent() is generated by the designer and sets up all controls
            // declared in login.Designer.cs (panel1, labels, textboxes, radio buttons, buttons).
            InitializeComponent();

            // Now, we will set up the login-specific panel and its controls programmatically.
            SetupLoginPanel();

            // Apply professional styling to the designer-generated controls.
            ApplyDesignerControlStyling();

            // Correctly parent radio buttons to the group box, as designer might place them directly on panel.
            //CorrectRadioButtonParenting();

            // Initialize the LoggedInUsername property
            LoggedInUsername = string.Empty;
        }

        /// <summary>
        /// Applies professional styling (fonts, colors, borders) to the controls
        /// that were generated by the Windows Forms Designer.
        /// </summary>
        private void ApplyDesignerControlStyling()
        {
            // --- Form Properties ---
            this.Text = "Car Store - User Authentication";
            this.Size = new Size(1000, 800); // Set a professional form size
            this.MinimumSize = new Size(500, 600); // Prevent too much shrinking
            this.BackColor = Color.FromArgb(0, 40, 85); // A soft dark navy blue
            this.FormBorderStyle = FormBorderStyle.FixedSingle; // Prevent resizing for consistent layout
            this.MaximizeBox = true; // Disable maximize button
            this.StartPosition = FormStartPosition.CenterScreen; // Center the form on screen

            // --- Panel 1 (Registration Panel) Styling ---
            panel1.Size = new Size(600, 550); // Size for the registration panel
            // Position below the toggle button, centered horizontally
            panel1.Location = new Point((this.ClientSize.Width - panel1.Width) / 2 - 8, 80);
            panel1.BackColor = Color.White; // White background for the panel
            panel1.BorderStyle = BorderStyle.FixedSingle; // Add a border
            panel1.Padding = new Padding(20); // Inner padding for controls
            panel1.BringToFront(); // Ensure registration panel is visible by default

            // --- Main Toggle Button (button2) Styling ---
            button2.Text = "Login"; // Initial text for the toggle button
            button2.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            button2.Size = new Size(180, 45);
            // Center the button horizontally at the top of the form
            button2.Location = new Point(215, 400);
            button2.BackColor = Color.FromArgb(70, 130, 180); // SteelBlue
            button2.ForeColor = Color.White;
            button2.FlatStyle = FlatStyle.Flat; // Flat style for modern look
            button2.FlatAppearance.BorderSize = 0; // No border

            // --- Apply styles to labels and textboxes within panel1 (registration) ---
            // These positions are relative to panel1
            int yPos = 30; // Starting Y position for controls within the panel
            int labelWidth = 150;
            int textBoxWidth = 280;
            int controlHeight = 30;
            int spacing = 45; // Vertical spacing between control groups

            // Label 1: Full Name
            label1.Text = "Full Name:";
            label1.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
            label1.Size = new Size(labelWidth, controlHeight);
            label1.Location = new Point(20, yPos);

            textBox1.PlaceholderText = "Enter your full name"; // Hint text
            textBox1.Font = new Font("Segoe UI", 10F);
            textBox1.Size = new Size(textBoxWidth, controlHeight);
            textBox1.Location = new Point(labelWidth + 30, yPos);
            textBox1.BorderStyle = BorderStyle.FixedSingle;
            yPos += spacing;

            // Label 2: Phone Number
            label2.Text = "Phone Number:";
            label2.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
            label2.Size = new Size(labelWidth, controlHeight);
            label2.Location = new Point(20, yPos);

            textBox2.PlaceholderText = "e.g., +2518985959898";
            textBox2.Font = new Font("Segoe UI", 10F);
            textBox2.Size = new Size(textBoxWidth, controlHeight);
            textBox2.Location = new Point(labelWidth + 30, yPos);
            textBox2.BorderStyle = BorderStyle.FixedSingle;
            yPos += spacing;

            // Label 3: Email
            label3.Text = "Email:";
            label3.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
            label3.Size = new Size(labelWidth, controlHeight);
            label3.Location = new Point(20, yPos);

            textBox3.PlaceholderText = "your.email@example.com";
            textBox3.Font = new Font("Segoe UI", 10F);
            textBox3.Size = new Size(textBoxWidth, controlHeight);
            textBox3.Location = new Point(labelWidth + 30, yPos);
            textBox3.BorderStyle = BorderStyle.FixedSingle;
            yPos += spacing;

            // Label 4: Password
            label4.Text = "Password:";
            label4.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
            label4.Size = new Size(labelWidth, controlHeight);
            label4.Location = new Point(20, yPos);

            textBox4.PlaceholderText = "Enter your password";
            textBox4.Font = new Font("Segoe UI", 10F);
            textBox4.Size = new Size(textBoxWidth, controlHeight);
            textBox4.Location = new Point(labelWidth + 30, yPos);
            textBox4.UseSystemPasswordChar = true; // Hide password characters (e.g., with '*')
            textBox4.BorderStyle = BorderStyle.FixedSingle;
            yPos += spacing;

            // Label 5: Gender
            label5.Text = "Gender:";
            label5.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
            label5.Size = new Size(labelWidth, controlHeight);
            label5.Location = new Point(20, yPos);

            // GroupBox for Radio Buttons (groupBox1)
            groupBox1.Text = ""; // No visible text for the group box itself
            groupBox1.Font = new Font("Segoe UI", 9F, FontStyle.Regular);
            groupBox1.Size = new Size(textBoxWidth, 100); // Adjusted size to fit radio buttons
            // Position to align with the Gender label
            groupBox1.Location = new Point(labelWidth + 30, yPos - 10);

            // Radio Buttons within the GroupBox
            radioButton1.Text = "Male";
            radioButton1.Font = new Font("Segoe UI", 9F);
            radioButton1.Size = new Size(100, 25);
            radioButton1.Location = new Point(10, 20); // Position within the group box

            radioButton2.Text = "Female";
            radioButton2.Font = new Font("Segoe UI", 9F);
            radioButton2.Size = new Size(100, 25);
            radioButton2.Location = new Point(10, 45);

            radioButton3.Text = "I prefer not to say";
            radioButton3.Font = new Font("Segoe UI", 9F);
            radioButton3.Size = new Size(150, 25);
            radioButton3.Location = new Point(10, 70);


            // Correctly parent radio buttons to the group box if they are added to the panel by designer
            if (panel1.Controls.Contains(radioButton1)) panel1.Controls.Remove(radioButton1);
            if (panel1.Controls.Contains(radioButton2)) panel1.Controls.Remove(radioButton2);
            if (panel1.Controls.Contains(radioButton3)) panel1.Controls.Remove(radioButton3);

            // Add them to the groupBox1
            if (!groupBox1.Controls.Contains(radioButton1)) groupBox1.Controls.Add(radioButton1);
            if (!groupBox1.Controls.Contains(radioButton2)) groupBox1.Controls.Add(radioButton2);
            if (!groupBox1.Controls.Contains(radioButton3)) groupBox1.Controls.Add(radioButton3);


            yPos += groupBox1.Height + 20; // Move yPos past the group box with some extra spacing

            // Button 1: Register
            button1.Text = "Register";
            button1.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            button1.Size = new Size(150, 45);
            // Center the button horizontally within the panel
            button1.Location = new Point((panel1.Width - button1.Width) / 2, yPos);
            button1.BackColor = Color.FromArgb(60, 179, 113); // MediumSeaGreen
            button1.ForeColor = Color.White;
            button1.FlatStyle = FlatStyle.Flat;
            button1.FlatAppearance.BorderSize = 0;
        }


        private void SetupLoginPanel()
        {
            pnlLogin = new Panel();
            pnlLogin.Name = "pnlLogin"; // Give the dynamically created panel a name
            pnlLogin.Size = new Size(600, 550); // Increased height to accommodate the new button
                                                // Position centered, slightly lower than register panel for visual separation
            pnlLogin.Location = new Point((this.ClientSize.Width - panel1.Width) / 2, 80);

            pnlLogin.BackColor = Color.White;
            pnlLogin.BorderStyle = BorderStyle.FixedSingle;
            pnlLogin.Padding = new Padding(20);
            pnlLogin.Visible = false; // Start with login panel hidden
            this.Controls.Add(pnlLogin); // Add to the form's controls

            int loginYPos = 50; // Starting Y position for controls within the login panel
            int loginLabelWidth = 100;
            int loginTextBoxWidth = 250;
            int loginControlHeight = 30;
            int loginSpacing = 60; // Vertical spacing

            // Label for Login Name
            labelLoginName = new Label();
            labelLoginName.Name = "labelLoginName"; // Give the label a name
            labelLoginName.Text = "Name:";
            labelLoginName.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
            labelLoginName.Size = new Size(loginLabelWidth, loginControlHeight);
            labelLoginName.Location = new Point(20, loginYPos);
            pnlLogin.Controls.Add(labelLoginName);

            textBoxLoginName = new TextBox();
            textBoxLoginName.Name = "textBoxLoginName"; // Give the textbox a name
            textBoxLoginName.PlaceholderText = "Enter your username or full name";
            textBoxLoginName.Font = new Font("Segoe UI", 10F);
            textBoxLoginName.Size = new Size(loginTextBoxWidth, loginControlHeight);
            textBoxLoginName.Location = new Point(loginLabelWidth + 30, loginYPos);
            textBoxLoginName.BorderStyle = BorderStyle.FixedSingle;
            pnlLogin.Controls.Add(textBoxLoginName);

            loginYPos += loginSpacing;

            // Label for Login Password
            labelLoginPassword = new Label();
            labelLoginPassword.Name = "labelLoginPassword"; // Give the label a name
            labelLoginPassword.Text = "Password:";
            labelLoginPassword.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
            labelLoginPassword.Size = new Size(loginLabelWidth, loginControlHeight);
            labelLoginPassword.Location = new Point(20, loginYPos);
            pnlLogin.Controls.Add(labelLoginPassword);

            textBoxLoginPassword = new TextBox();
            textBoxLoginPassword.Name = "textBoxLoginPassword"; // Give the textbox a name
            textBoxLoginPassword.PlaceholderText = "Enter your password";
            textBoxLoginPassword.Font = new Font("Segoe UI", 10F);
            textBoxLoginPassword.Size = new Size(loginTextBoxWidth, loginControlHeight);
            textBoxLoginPassword.Location = new Point(loginLabelWidth + 30, loginYPos);
            textBoxLoginPassword.UseSystemPasswordChar = true; // Hide password characters
            textBoxLoginPassword.BorderStyle = BorderStyle.FixedSingle;
            pnlLogin.Controls.Add(textBoxLoginPassword);

            loginYPos += loginSpacing;

            // Button to Perform Login (specific to the login panel)
            buttonPerformLogin = new Button();
            buttonPerformLogin.Name = "buttonPerformLogin"; // Give the button a name
            buttonPerformLogin.Text = "Login";
            buttonPerformLogin.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            buttonPerformLogin.Size = new Size(150, 45);
            // Center the button horizontally within the login panel
            buttonPerformLogin.Location = new Point(150, loginYPos);
            buttonPerformLogin.BackColor = Color.FromArgb(255, 140, 0); // DarkOrange
            buttonPerformLogin.ForeColor = Color.White;
            buttonPerformLogin.FlatStyle = FlatStyle.Flat;
            buttonPerformLogin.FlatAppearance.BorderSize = 0;
            buttonPerformLogin.Click += new EventHandler(this.buttonPerformLogin_Click);
            pnlLogin.Controls.Add(buttonPerformLogin);

            loginYPos += 60; // Add extra spacing before the register button

            // Button to Switch to Registration Panel
            Button buttonSwitchToRegister = new Button();
            buttonSwitchToRegister.Name = "buttonSwitchToRegister"; // Give the button a name
            buttonSwitchToRegister.Text = "Don't have an account? Register";
            buttonSwitchToRegister.Font = new Font("Segoe UI", 9F, FontStyle.Regular);
            buttonSwitchToRegister.Size = new Size(250, 35);
            buttonSwitchToRegister.Location = new Point(110, loginYPos);
            buttonSwitchToRegister.BackColor = Color.Transparent;
            buttonSwitchToRegister.ForeColor = Color.FromArgb(70, 130, 180); // SteelBlue
            buttonSwitchToRegister.FlatStyle = FlatStyle.Flat;
            buttonSwitchToRegister.FlatAppearance.BorderSize = 0;
            buttonSwitchToRegister.Cursor = Cursors.Hand; // Change cursor to hand when hovering
            buttonSwitchToRegister.Click += (s, e) =>
            {
                // Toggle visibility when clicked
                pnlLogin.Visible = false;
                panel1.Visible = true;
                button2.Text = "Login"; // Update the main toggle button text
                this.Text = "Car Store - User Registration"; // Update form title
            };
            pnlLogin.Controls.Add(buttonSwitchToRegister);
        }
        // ... existing event handlers ...

        private void textBox1_TextChanged(object sender, EventArgs e)
        {
            // Event for Full Name textbox.
            // You can add real-time validation or other logic here if needed.
        }

        private void textBox2_TextChanged(object sender, EventArgs e)
        {
            // Event for Phone Number textbox.
        }

        private void textBox3_TextChanged(object sender, EventArgs e)
        {
            // Event for Email textbox.
        }

        private void textBox4_TextChanged(object sender, EventArgs e)
        {
            // Event for Password textbox.
        }

        private void radioButton1_CheckedChanged(object sender, EventArgs e)
        {
            // Event for Male radio button.
        }

        private void radioButton2_CheckedChanged(object sender, EventArgs e)
        {
            // Event for Female radio button.
        }

        private void radioButton3_CheckedChanged(object sender, EventArgs e)
        {
            // Event for "I prefer not to say" radio button.
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {
            // Event handler for the main registration panel (panel1).
        }

        private void label1_Click(object sender, EventArgs e)
        {
            // Event for Full Name label.
        }

        private void label2_Click(object sender, EventArgs e)
        {
            // Event for Phone Number label.
        }

        private void label3_Click(object sender, EventArgs e)
        {
            // Event for Email label.
        }

        private void label4_Click(object sender, EventArgs e)
        {
            // Event for Password label.
        }

        private void label5_Click(object sender, EventArgs e)
        {
            // Event for Gender label.
        }

        private void label6_Click(object sender, EventArgs e)
        {
            // This label was not explicitly mapped in the UI description,
            // but the handler is kept as provided in your original code.
        }

        private void label7_Click(object sender, EventArgs e)
        {
            // This label was not explicitly mapped in the UI description,
            // but the handler is kept as provided in your original code.
        }

        private void groupBox1_Enter(object sender, EventArgs e)
        {
            // Event for the Gender GroupBox.
        }

        private void login_Load(object sender, EventArgs e)
        {
            // Event that fires when the form loads.
        }

        // --- Logic for the Register and Login Buttons ---

        private void button1_Click(object sender, EventArgs e)
        {
            // Handler for the "Register" button (button1).
            string fullName = textBox1.Text.Trim();
            string phoneNumber = textBox2.Text.Trim();
            string email = textBox3.Text.Trim();
            string password = textBox4.Text; // Password is not trimmed for security reasons

            string gender = "Not specified";
            if (radioButton1.Checked) gender = "Male";
            else if (radioButton2.Checked) gender = "Female";
            else if (radioButton3.Checked) gender = "I prefer not to say";

            // Basic validation: Check if essential fields are filled
            if (string.IsNullOrEmpty(fullName) || string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password))
            {
                MessageBox.Show("Please fill in all required fields (Full Name, Email, Password).", "Registration Error", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            // Use the DatabaseConnection to register the user
            bool registrationSuccess = DatabaseConnection.RegisterUser(fullName, email, password, phoneNumber, gender);

            if (registrationSuccess)
            {
                MessageBox.Show("Registration Successful! You can now login.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);

                // Optionally clear the registration fields after successful registration
                textBox1.Clear();
                textBox2.Clear();
                textBox3.Clear();
                textBox4.Clear();
                radioButton1.Checked = false;
                radioButton2.Checked = false;
                radioButton3.Checked = false;

                // Switch to login panel after successful registration
                panel1.Visible = false;
                pnlLogin.Visible = true;
                button2.Text = "Switch to Register";
                this.Text = "Car Store - User Login";
            }
            else
            {
                MessageBox.Show("Registration failed. Please try again. (Username or Email might already exist)", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void button2_Click(object sender, EventArgs e)
        {
            // Handler for the main toggle button (button2).
            // This switches visibility between the registration panel (panel1) and the login panel (pnlLogin).
            if (panel1.Visible)
            {
                panel1.Visible = false; // Hide registration panel
                pnlLogin.Visible = true; // Show login panel
                button2.Text = "Switch to Register"; // Change toggle button text
                this.Text = "Car Store - User Login"; // Update form title
            }
            else
            {
                panel1.Visible = true; // Show registration panel
                pnlLogin.Visible = false; // Hide login panel
                button2.Text = "Switch to Login"; // Change toggle button text
                this.Text = "Car Store - User Registration"; // Update form title
            }
        }

        /// <summary>
        /// Handler for the "Login" button located within the login panel.
        /// This performs the actual login attempt.
        /// </summary>
        private void buttonPerformLogin_Click(object sender, EventArgs e)
        {
            string loginName = textBoxLoginName.Text.Trim();
            string loginPassword = textBoxLoginPassword.Text; // Password not trimmed

            // Basic validation for login fields
            if (string.IsNullOrEmpty(loginName) || string.IsNullOrEmpty(loginPassword))
            {
                MessageBox.Show("Please enter both Name and Password to log in.", "Login Error", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            // Use the DatabaseConnection to validate the user
            var (success, isAdmin) = DatabaseConnection.ValidateUser(loginName, loginPassword);

            if (success)
            {
                // Set the public property and DialogResult before closing
                LoggedInUsername = loginName;
                DialogResult = DialogResult.OK;

                if (isAdmin)
                {
                    // If user is admin, show the AdminPage form
                    AdminPage adminForm = new AdminPage();
                    this.Hide(); // Hide the login form
                    adminForm.ShowDialog(); // Show the admin form modally
                    this.Close(); // Close the login form after AdminPage is closed
                }
                else
                {
                    // If user is not admin, show success message or a regular user form
                    MessageBox.Show("Login Successful! Welcome to Car Store.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    // Close the login form, Form1 will handle showing the main content
                    this.Close();
                }
            }
            else
            {
                // If validation failed
                MessageBox.Show("Invalid Name or Password. Please try again.", "Login Failed", MessageBoxButtons.OK, MessageBoxIcon.Error);

                // Optionally clear login fields after failed attempt
                textBoxLoginName.Clear();
                textBoxLoginPassword.Clear();
            }
        }
        // ... rest of the class ...
    }
}