using System;
using System.Collections.Generic; // Keep if needed by designer or other parts
using System.ComponentModel; // Keep if needed by designer or other parts
using System.Data; // Keep if needed by designer or other parts
using System.Drawing;
using System.Linq; // Keep if needed by other parts
using System.Text; // Keep if needed by other parts
using System.Threading.Tasks; // Keep if needed by other parts
using System.Windows.Forms;
using carstore; // Keep if needed by DatabaseConnection or other classes

namespace carstore
{
    public partial class payment : Form
    {
        public payment()
        {
            InitializeComponent();
            // Set the form's start position to CenterScreen here or in designer
            this.StartPosition = FormStartPosition.CenterScreen;
            // Set the form's background color here or in designer
            this.BackColor = Color.FromArgb(0, 40, 85); // Example color
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {
            // If panel1 is a container panel and you set its background color here,
            // ensure the color is applied. However, setting colors in InitializeComponents
            // or the constructor is generally preferred.
            // panel1.BackColor = Color.FromArgb(0, 40, 85);
        }

        private void button1_Click(object sender, EventArgs e)
        {
            // Assuming button1 is your "Submit Payment" or "Complete Order" button

            // Simulate payment processing (you can add more dummy logic here if desired)

            MessageBox.Show("Payment Successful!", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);

            // *** IMPORTANT CHANGES HERE ***
            // 1. Set the DialogResult to OK to indicate success to the calling form (Form1)
            this.DialogResult = DialogResult.OK;

            // 2. Close the payment form
            this.Close();
        }

        // Optional: Add a FormClosing event handler to set DialogResult if form is closed unexpectedly
        private void payment_FormClosing(object sender, FormClosingEventArgs e)
        {
            // If the DialogResult hasn't been explicitly set to OK (by clicking button1),
            // set it to Cancel to indicate the payment process was not completed successfully.
            if (this.DialogResult != DialogResult.OK)
            {
                this.DialogResult = DialogResult.Cancel;
            }
        }

        // Keep other event handlers generated by the designer if they exist (e.g., payment_Load)
        // private void payment_Load(object sender, EventArgs e) { }
    }
}